version: '3'

services:
  app:
    build:
      context: . 
    ports:
      - "8080:3000" 
    depends_on:
      - mongodb
      - redis
            
  mongodb:
    image: mongo:latest
    container_name: nest_mongodb
    ports:
      - "27017:27017" 

  redis:
    image: redis:latest
    container_name: nest_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
